name: Docker Workflow

on:
  - push
  
jobs: 
  docker_build: 
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Docker Build 
      run: docker build -t docker.io/badarudeen/web-app:latest .

    - name: Docker Login
      run: docker login --username=${{ vars.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}

    - name: Docker Publish 
      run: docker push docker.io/badarudeen/web-app:latest

  docker_deploy:
    needs: docker_build
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Docker Login
        run: docker login --username=${{ vars.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
      - name: Docker Run
        run: docker run -d -p 8080:80 docker.io/efotsowoe/resume-app:latest
